# Generated by Django 6.0.5 on 2026-05-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kan_mind', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('owner_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Board',
        ),
    ]
