# Generated by Django 6.0.5 on 2026-05-12 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kan_mind', '0003_alter_task_assignee_id_alter_task_reviewer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assignee_id',
            new_name='assignee',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='reviewer_id',
            new_name='reviewer',
        ),
    ]
