# Generated by Django 6.0.5 on 2026-05-15 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kan_mind", "0004_rename_assignee_id_task_assignee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="kan_mind.board",
            ),
        ),
    ]
