# Generated by Django 6.0.5 on 2026-05-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kan_mind", "0005_alter_task_board"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("low", "low"), ("medium", "medium"), ("high", "high")],
                max_length=10,
            ),
        ),
    ]
