# Generated by Django 6.0.5 on 2026-05-08 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kan_mind', '0005_alter_board_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
