# Generated by Django 6.0.5 on 2026-05-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kan_mind", "0008_rename_task_id_comment_task_alter_comment_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
